---
version: '3.5'
services:
  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 8080:8080
  frontend:
    image: app-front:latest
    build: ./frontend
    restart: unless-stopped
    depends_on: 
      - backend
  backend:
    image: app-back:latest
    build: ./backend
    restart: unless-stopped
    depends_on: 
      - database
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://database:3306/fullstack'
  database:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: 'fullstack'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"